server {
    #listen for incoming ipv4 traffic on port 443
    #ssl = accept only encrypted connections
    #[::]:443 = same as above but for ipv6 traffic
    #server_name = bind this server block to specific domain name (ignore anything else)
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name azsaleh.42.fr;

    #use only either tls v1.2 or v1.3
    #ssl_certificate = tells nginx where to find cryptographic certificate and private key
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    #root = point to folder containing website files (wordpress)
    #index = tells nginx which file to look when user visits root domain (https://azsaleh.42.fr)
    root /var/www/html;
    index index.php index.html;

    #catch any incoming url request that ends with .php
    location ~ \.php$ {
        #fastcgi_params = imports a default configuration file that php-fpm need to understand web requests (environment variables - request method, query strings, browser details, etc)
        #fastcgi_index = append index.php to the request before passing it to php
        #fastcgi_pass = pass php requests to wordpress via port 9000 (via docker network)
        #SCRIPT_FILENAME = tells wordpress which php file to execute
        #document_root = /var/www/html (as defined above)
        #fastcgi_script_name = file user asked for (ie /index.php)
        #HTTP_HOST = explicitly pass the original browser host (including custom ports) to PHP
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $http_host;
    }

    #catch all request if location context for php requests above does not work
    location / {
        #pretty permalinks
        #$uri = check if file exist first
        #$uri/ = check if directory existsts second
        #/index.php?$args = pass request to /index.php with original query and let wordpress to internally figure out what page to show user
        try_files $uri $uri/ /index.php?$args;
    }
}