services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=$$(cat /run/secrets/db_root_password)"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/credentials.txt:/run/secrets/credentials:ro
    networks:
      - inception
    healthcheck:
      test: ["CMD", "sh", "-c", "cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/azrulsaleh/data/mariadb

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/azrulsaleh/data/wordpress

networks:
  inception:
    name: inception
    driver: bridge